seed: 22
data:
  path: data/data.npy
time_data:
  path: data/time_data.npy
model:
  lstm_input_size: 32
  lstm_hidden_size: 64
  lstm_num_layers: 2
  static_input_size: 63
  static_hidden_size: 64
  merged_hidden_size: 64
  output_size: 1
trainer:
  max_epochs: 100
  batch_size: 32
  gpus: 1
  gradient_clip_val: 0.5
logger:
  save_dir: logs
  name: model
  version: 1 